import VMdijs from 'vue-mdijs';
import {
  mdiClipboardTextOutline,
  mdiViewGridOutline,
  mdiViewListOutline,
  mdiGithub,
  mdiHomeOutline,
  mdiConsole,
  mdiPlus,
  mdiClose,
  mdiMagnify,
  mdiFilterOutline,
  mdiFolderOpenOutline,
  mdiStarOutline,
  mdiPencilOutline,
  mdiDeleteOutline,
  mdiPuzzleOutline,
  mdiStar,
  mdiAlertOutline,
  mdiDownloadOutline,
  mdiInformationOutline,
  mdiImageOutline,
} from '@mdi/js';

VMdijs.add({
  mdiClipboardTextOutline,
  mdiViewGridOutline,
  mdiViewListOutline,
  mdiGithub,
  mdiHomeOutline,
  mdiConsole,
  mdiPlus,
  mdiClose,
  mdiMagnify,
  mdiFilterOutline,
  mdiFolderOpenOutline,
  mdiStarOutline,
  mdiPencilOutline,
  mdiDeleteOutline,
  mdiPuzzleOutline,
  mdiStar,
  mdiAlertOutline,
  mdiDownloadOutline,
  mdiInformationOutline,
  mdiImageOutline,
});

export default VMdijs;
